export enum ErrorCode {
  // Auth
  FORBIDDEN = 'FORBIDDEN',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  // Session
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_INVALID_OR_EXPIRED = 'SESSION_INVALID_OR_EXPIRED',
  
  // Workspace
  WORKSPACE_SLUG_EXISTS = 'WORKSPACE_SLUG_EXISTS',
  WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND',
  
  // Validation
  VAL_ERROR = 'VALIDATION_ERROR',

  VAL_NAME_EMPTY = 'VAL_NAME_EMPTY',
  VAL_NAME_NOT_STRING = 'VAL_NAME_NOT_STRING',
  VAL_NAME_TOO_SHORT = 'VAL_NAME_TOO_SHORT',
  
  VAL_SLUG_EMPTY = 'VAL_SLUG_EMPTY',
  VAL_SLUG_NOT_STRING = 'VAL_SLUG_NOT_STRING',
  VAL_SLUG_PATTERN_INVALID = 'VAL_SLUG_PATTERN_INVALID',

  VAL_EMAIL_INVALID = 'VAL_EMAIL_INVALID',

  VAL_PASSWORD_EMPTY = 'VAL_PASSWORD_EMPTY',
  VAL_PASSWORD_WEAK = 'VAL_PASSWORD_WEAK',

  // General
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
}